name: 'Aliyun Cdn Api'
description: 'supports all standard aliyun cdn apis for easy use in github actions'
author: 'weirui88888'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
