name: 'Aliyun Cdn Api'
description: 'supports all standard aliyun cdn apis for easy use in github actions'
author: 'weirui88888'
inputs:
  accessKeyId:
    required: true
    description: 'accessKeyId is required'
  accessKeySecret:
    required: true
    description: 'accessKeySecret is required'
outputs:
  DescribeCdnDomainConfigs:
    description: 'The DescribeCdnDomainConfigs of your support'
runs:
  using: 'node12'
  main: 'dist/index.js'
