name: 'Aliyun Cdn Sdk'
description: 'supports all standard aliyun cdn apis for easy use in github actions'
author: 'weirui88888'
inputs:
  accessKeyId:
    required: true
    description: 'accessKeyId is required'
  accessKeySecret:
    required: true
    description: 'accessKeySecret is required'
  parameters:
    required: true
    description: 'request params,Request parameters consist of base request parameters and API custom parameters'
outputs:
  responseBody:
    description: 'responseBody with your input'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'cloud'
  color: 'yellow'
