name: 'use this action with local file'
on: [push]

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      # use this action in current package
      - uses: actions/checkout@v3

      - name: View Folder
        run: |
          ls
          cat package.json

      - name: Test DescribeCdnDomainConfigs
        id: getDescribeCdnDomainConfigsConfig
        uses: ./
        with:
          accessKeyId: ${{secrets.ALI_ACCESS_KEY_ID}}
          accessKeySecret: ${{secrets.ALI_ACCESS_KEY_SECRET}}
          parameters: '{"action": "DescribeCdnDomainConfigs", "domainName": "aliossupload.newarray.vip", "functionNames": "filetype_based_ttl_set,set_req_host_header" }'

      - name: Test DescribeCdnDeletedDomains
        id: getDescribeCdnDeletedDomains
        uses: ./
        with:
          accessKeyId: ${{secrets.ALI_ACCESS_KEY_ID}}
          accessKeySecret: ${{secrets.ALI_ACCESS_KEY_SECRET}}
          parameters: '{"action": "DescribeCdnDeletedDomains", "pageNumber": 1, "pageSize":10}'

      - name: View
        run: |
          echo ${{steps.getDescribeCdnDomainConfigsConfig.outputs.responseBody}}
          echo ${{steps.getDescribeCdnDeletedDomains.outputs.responseBody}}
