name: 'Demo<RefreshObjectCaches>'
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: RefreshObjectCaches
        id: RefreshObjectCaches
        uses: weirui88888/aliyun-cdn-sdk@v1.0.2
        env:
          ttl_config: '{"action": "RefreshObjectCaches", "ObjectPath": "https://aliossupload.newarray.vip/", "ObjectType": "Directory" }'
        with:
          accessKeyId: ${{secrets.ALI_ACCESS_KEY_ID}}
          accessKeySecret: ${{secrets.ALI_ACCESS_KEY_SECRET}}
          parameters: ${{env.ttl_config}}

      - name: View ResponseBody
        run: |
          echo "---------------------------------------------------------------"
          echo ${{steps.RefreshObjectCaches.outputs.responseBody}}
          echo "---------------------------------------------------------------"
