name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: View Folder
        run: |
          ls
          cat package.json

      - name: Test DescribeCdnDomainConfigs
        id: getDescribeCdnDomainConfigsConfig
        uses: ./
        with:
          accessKeyId: ${{secrets.ALI_ACCESS_KEY_ID}}
          accessKeySecret: ${{secrets.ALI_ACCESS_KEY_SECRET}}
          parameters: '{"action": "DescribeCdnDomainConfigs", "domainName": "hexo.newarray.vip", "functionNames": "filetype_based_ttl_set" }'

      - name: Test StartCdnDomain
        id: getStartCdnDomain
        uses: ./
        with:
          accessKeyId: ${{secrets.ALI_ACCESS_KEY_ID}}
          accessKeySecret: ${{secrets.ALI_ACCESS_KEY_SECRET}}
          parameters: '{"action": "StartCdnDomain", "domainName": "gus.newarray.vip"}'

      - name: View
        run: |
          echo ${{steps.getDescribeCdnDomainConfigsConfig.outputs.responseBody}}
          echo ${{steps.getStartCdnDomain.outputs.responseBody}}
